osx_image: xcode10.1
language: objective-c
xcode_project: AlchemyTest.xcodeproj # path to your xcodeproj folder
xcode_scheme: AlchemyTest
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 7

  # Only if app has Carthage dependencies
  # - carthage bootstrap --verbose

script:
  - carthage build --no-skip-current
  - xcodebuild test -project AlchemyTest.xcodeproj -scheme AlchemyTest -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 7' | xcpretty --test --color
