osx_image: xcode10.1
language: objective-c
xcode_project: AlchemyTest/AlchemyTest.xcodeproj # path to your xcodeproj folder
xcode_scheme: AlchemyTest
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 7
before_install:
  - brew update ; brew upgrade carthage

  # Only if app has Carthage dependencies
  # - carthage bootstrap --verbose

script:
  - carthage build --no-skip-current
  - xcodebuild test -project AlchemyTest/AlchemyTest.xcodeproj -scheme AlchemyTest -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 7'
